version: '3.7'

services:
  nginx:
    build: ./nginx
    image: starter_nginx
    container_name: starter-nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
    networks:
      - backend
      - frontend

  backend:
    build: ./backend
    image: starter_backend
    container_name: starter-backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
      - db
    volumes:
      - ./backend:/backend
      - static:/backend/static

  frontend:
    build: ./frontend
    image: starter_frontend
    container_name: starter-frontend
    stdin_open: true
    networks:
      - frontend
    volumes:
      - ./frontend:/frontend

  db:
    build: ./db
    image: starter_db
    container_name: starter-db
    env_file:
      - .env
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:
  frontend:
  db:

volumes:
  static:
  db-data:
