version: '3.7'

services:
  backend:
    build: ./backend
    image: starter_backend
    container_name: starter-backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - backend
    volumes:
      - ./backend:/backend
      - static:/backend/static

networks:
  backend:

volumes:
  static:
